version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/usr/src/app
    environment:
      - MONGO_URI=mongodb://mongodb:27017/tpv

  mongodb:
    image: mongo:5.0
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  carta:
    build:
      context: ./carta
    ports:
      - "3001:80"

  tpv:
    build:
      context: ./tpv
    ports:
      - "3002:80"

volumes:
  mongo-data:
